<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mail_pass</name>
   <tag></tag>
   <elementGuidId>210a04bd-7925-46d0-8e51-5d1f118eb2d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='vtexIdContainer']/div[1]/div[2]/div[2]/div[1]/div[3]/ul[1]/li[3]/button[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
