<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pantalones</name>
   <tag></tag>
   <elementGuidId>8ebf1d3a-88e3-4402-86a2-62e586aa8095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/a[1]/div[1]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
