<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verificar</name>
   <tag></tag>
   <elementGuidId>562566d9-9fd2-4680-a8d7-7441b5a89251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='vtexIdContainer']/div[1]/div[2]/div[3]/div[1]/form[1]/div[3]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
