<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vestidos</name>
   <tag></tag>
   <elementGuidId>f38b6083-b43d-4557-8dd8-5a2915e518c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[7]/div[1]/a[1]/div[1]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
