<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vestido</name>
   <tag></tag>
   <elementGuidId>90f3e6f8-c17b-4720-9d55-523f19681458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/a[1]/div[1]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
