<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>campo_1</name>
   <tag></tag>
   <elementGuidId>30319524-0b56-446a-9af6-66a006173ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//INPUT[@id='number1Field']/self::INPUT</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
