<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Borrar_btnK</name>
   <tag></tag>
   <elementGuidId>01f1a051-99e9-47cb-84eb-9ebd70826f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8488587-4c6f-4ee0-a0c2-a8bcb2fb964d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gNO89b</value>
      <webElementGuid>21bd3def-f788-4f94-9583-7918054f704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar con Google</value>
      <webElementGuid>7141fd5f-9407-43a8-9a68-ac6b1349f03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buscar con Google</value>
      <webElementGuid>05465cfe-a118-499a-a07c-33e605d7c7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>27e89c8c-8885-4da5-aa5a-1fa3c2c11cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa11c3ff-7c9b-4238-8429-08cae9d0ae51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95bce3f6-bc9c-47f3-aca0-8a6aa7ffae89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>46220fd8-20a6-45d3-80d3-5c9a0840d60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwjFmJW7lOiBAxWMUkEAHSILBnwQ4dUDCAo</value>
      <webElementGuid>9188e3a7-62e3-44d9-9ee9-9ca0e6b36e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf emcav&quot;]/div[@class=&quot;UUbT9 EyBRub&quot;]/div[@class=&quot;aajZCb&quot;]/div[@class=&quot;lJ9FBc&quot;]/center[1]/input[@class=&quot;gNO89b&quot;]</value>
      <webElementGuid>e6e8d7a6-32ab-4f75-85b7-45efd950a78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnK']</value>
      <webElementGuid>26a7ac89-189b-479e-98f9-ab5740155e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7b2f4cf8-8bd1-4c7b-8299-72017287900b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnK' and @type = 'submit']</value>
      <webElementGuid>b33ce14b-ca61-42e8-a190-dee25bc4136f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
