<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Abrir chat_mc-closeModal</name>
   <tag></tag>
   <elementGuidId>75c0fe31-789c-4058-aa0b-cc3ab01e3c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mc-closeModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupSignupForm_0']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a94b9dc-0fc0-4fb2-817e-5ed341c55245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mc-closeModal</value>
      <webElementGuid>3a22d95d-0f03-4aea-987f-5e71385009a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>close-mc-modal</value>
      <webElementGuid>417ec83e-4949-4a6a-a00b-a76b4bf9a77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>modalClose</value>
      <webElementGuid>407031da-d4ad-41b9-884e-21191ee860f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupSignupForm_0&quot;)/div[@class=&quot;mc-modal&quot;]/div[@class=&quot;mc-closeModal&quot;]</value>
      <webElementGuid>ac7c8311-a631-42a8-9d57-c6666c4e950e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupSignupForm_0']/div[2]/div</value>
      <webElementGuid>959a773f-7e4e-4f13-a8f0-5fde2da8dac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div</value>
      <webElementGuid>f2581767-4366-49d8-9929-0bb16d72e3e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
