<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Trminos y condiciones Bonos_attachment-_30bda9</name>
   <tag></tag>
   <elementGuidId>65eb3eb2-5d69-4bf7-a0a3-ceeac1195e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image_1521479080 > div.img-inner.dark > img.attachment-large.size-large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='image_1521479080']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>14c90e05-cb2b-46c9-beb6-1707f70c5701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>939</value>
      <webElementGuid>53b9c3ea-5499-4542-80e7-3c8cae5a90f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>8c50a2ef-cdde-4112-8c54-85d3bae9ac76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-939x400.png</value>
      <webElementGuid>0723329a-24df-4d3f-a561-e207e11a3579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large</value>
      <webElementGuid>efbddabb-0b05-400d-a16b-4b3a60e8808d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>eedfd8f6-ca8c-4017-980b-27e9cda840cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-939x400.png 939w, https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-800x341.png 800w, https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-768x327.png 768w, https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-510x217.png 510w, https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40.png 1080w</value>
      <webElementGuid>f2b44505-052c-40af-ad6a-5e1d41c11ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 939px) 100vw, 939px</value>
      <webElementGuid>345c7bdf-bc79-47ab-a6dc-f0979180c60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image_1521479080&quot;)/div[@class=&quot;img-inner dark&quot;]/img[@class=&quot;attachment-large size-large&quot;]</value>
      <webElementGuid>a1d34f13-fc91-4a93-931e-80eff0e28a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='image_1521479080']/div/img</value>
      <webElementGuid>ab2554cb-44ab-4d2e-9276-0020bdc6bd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-939x400.png')])[2]</value>
      <webElementGuid>5aaf1036-8727-4017-97d3-67aadd07c434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>662f130b-c64b-444f-9b20-b742a32f5371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://puntonetinsuperablesas.com/wp-content/uploads/2023/10/caixun40-939x400.png']</value>
      <webElementGuid>23bfc66e-68c8-423e-a323-a99e806bbb4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
