<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path__arrow</name>
   <tag></tag>
   <elementGuidId>62075024-a1ad-4da9-b3e8-93090bbb8522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.large-columns-5.medium-columns-4.small-columns-2.row-small.row-full-width.has-shadow.row-box-shadow-1.row-box-shadow-5-hover.slider.row-slider.slider-nav-circle.slider-nav-outside.slider-nav-push.flickity-enabled.is-draggable > button.flickity-button.flickity-prev-next-button.next > svg.flickity-button-icon > path.arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>0a80a01b-43bb-4182-8f37-66b0e6359d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z</value>
      <webElementGuid>be247ada-36c8-4da2-b1f7-8ce714f78aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>ee9896c4-e8e3-40f5-9154-b41a813b4258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(100, 100) rotate(180) </value>
      <webElementGuid>c83edb5b-73c7-4cc7-b0ed-af55a930ceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-1260742417&quot;)/div[@class=&quot;col medium-11 small-11 large-12&quot;]/div[@class=&quot;col-inner&quot;]/div[@class=&quot;row large-columns-5 medium-columns-4 small-columns-2 row-small row-full-width has-shadow row-box-shadow-1 row-box-shadow-5-hover slider row-slider slider-nav-circle slider-nav-outside slider-nav-push flickity-enabled is-draggable&quot;]/button[@class=&quot;flickity-button flickity-prev-next-button next&quot;]/svg[@class=&quot;flickity-button-icon&quot;]/path[@class=&quot;arrow&quot;]</value>
      <webElementGuid>b99e19d5-7d28-44f0-b5e5-5292b3d51839</webElementGuid>
   </webElementProperties>
</WebElementEntity>
