<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_userEmail</name>
   <tag></tag>
   <elementGuidId>73ff4289-4f23-4f27-9e29-d017085ac223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de35bf3f-6036-4110-9fb1-37d28c72625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76e387a6-2e0a-4806-ba41-f0952e83949d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@example.com</value>
      <webElementGuid>f8b2adb6-c81a-4101-9a73-4d394876c3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>17c74799-34a7-4465-8758-638e5daf2920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userEmail</value>
      <webElementGuid>e5fb2b68-47a8-4f55-b08b-2daed964100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-sm-2 form-control</value>
      <webElementGuid>d68b5bcc-265f-46cf-ae2a-45857a5755d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userEmail&quot;)</value>
      <webElementGuid>fdd24e2d-4d2c-4c29-ad78-952aaa2ff9a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userEmail']</value>
      <webElementGuid>23f7ae03-c0dc-45c2-96fc-c91eaffa318b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userEmail-wrapper']/div[2]/input</value>
      <webElementGuid>86099920-d5f5-48bd-9ba7-eca8acdee2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>71556059-d078-4fa8-b2e8-d3d805ef4655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'name@example.com' and @type = 'email' and @id = 'userEmail']</value>
      <webElementGuid>d05a7dc1-48f5-41c1-80a2-7f02f9cbf481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
