<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__mc-closeModal</name>
   <tag></tag>
   <elementGuidId>42ec38a6-8ece-487b-86ed-b6c8a3abc37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mc-closeModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupSignupForm_0']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>91d844f0-1a90-423a-8842-f8d7a4b03298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mc-closeModal</value>
      <webElementGuid>b7206a12-ab02-4821-b22f-1af34117109d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>close-mc-modal</value>
      <webElementGuid>c464beb0-4fff-44f7-8a09-dbe07bf50f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>modalClose</value>
      <webElementGuid>4850404b-2d38-4435-ae2b-35530b37dd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupSignupForm_0&quot;)/div[@class=&quot;mc-modal&quot;]/div[@class=&quot;mc-closeModal&quot;]</value>
      <webElementGuid>61ce562d-a32d-441e-98d7-fe305341bb9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupSignupForm_0']/div[2]/div</value>
      <webElementGuid>64f12953-88d0-4463-9b02-8707955edb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div</value>
      <webElementGuid>77d3590c-e79a-4993-a638-4aed315f023f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
